### ISSUE TITLE
Empty commits created

### ISSUE THREAD

**Issue by patrikturi** [gabor-boros/hammurabi#204]
**Describe the bug**

The hammurabi branch also contains empty commits. In my opinion, it is enough to list the executed rules on the PR page and don't have to clutter the repository with it.

**To Reproduce**

Not sure if this always happens or only under certain conditions. I can investigate further if you agree to remove them.

**Screenshots**

<img width="958" alt="Image 2020-09-07 at 11 34 58 PM" src="https://user-images.githubusercontent.com/13408366/92417509-df14e900-f162-11ea-95fa-1fd86ed2c62c.png">

**Comment by gabor-boros** [comment]
Nice finding @patrikturi! I've seen this before, but I wasn't able to reproduce. I have an idea what could be the root cause, but I would need some time to validate.

Probably I'll be able to look into this (and fix it) this week.

I guess the issue comes up if, and only if the hammurabi branch already exists, so the script runs for the second time (and the branch isn't closed yet).

**Comment by patrik-turi** [comment]
Let me check if I can reproduce and fix it.

**Comment by patrikturi** [comment]
Let me check if I can reproduce and fix it.

**Comment by patrikturi** [comment]
What happens is that `hammurabi.log` makes the repo dirty so every Law is committed even if there were no changes.

It would be a more robust approach to try to stage the files first, then commit if there is anything staged. It would also protect against the case if the Rule is staging different files than it modified due to misconfiguration (even better if we can check that).

What do you think?

**Comment by gabor-boros** [comment]
Hmm, I totally agree with you. Having a more fail proof and bit more robust approach could be more helpful on the long run.

**Comment by gabor-boros** [comment]
@patrikturi I had no time last week, but I did not forgot this issue 😇

**Comment by gabor-boros** [comment]
@patrikturi So I just checked this issue again.

We [already adding](https://github.com/gabor-boros/hammurabi/blob/master/hammurabi/mixins.py#L81) the changes to the stage before committing anything. The issue is with checking if we should do a commit or not [based on the state](https://github.com/gabor-boros/hammurabi/blob/master/hammurabi/mixins.py#L38) of the working tree, and not the stage.

This means that your point is still valid, but from a different angle. We could do the following:

1. Check for dirty working tree -> required for new files which are not yet tracked and so on
2. Add/Remove the desired changes to the stage
3. Commit (if and only if), the stage contains something

Probably the 3. point could be covered with checking `git diff --staged`.

I will fix it soon, though the release will happen at the end of the week. Not an issue for you guys, since the execution is scheduled for Monday, and I'll notify DX (FYI @uvegla / @balazs-tothfalussy) about this bug fix :blush:
